[package]
name = "freecord"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.14.0-dev", features = [
    "wgpu",
    "tiny-skia",
    "tokio",
    "image",
    "lazy",
    "advanced",
] }
tokio = { version = "1.47.1", features = ["rt", "fs", "io-util", "process"] }
tokio-stream = { version = "0.1.17", features = ["fs"] }
futures = "0.3.31"
socket2 = "0.6.0"
serde = { version = "1.0.219", features = ["derive", "rc"] }
serde_ignored = "0.1.12"
ed25519-dalek = { version = "2.2.0", features = ["rand_core", "alloc", "pkcs8", "pem"] }
rand = "0.8.0"
indexmap = { version = "2.11.0", features = ["std", "serde"] }
dirs-next = "2.0.0"
open = "5.3.2"
log = { version = "0.4.27", features = ["std"] }
fern = "0.7.1"
thiserror = "2.0.15"
anyhow = "1.0.99"
chrono = { version = "0.4.41", features = ["serde"] }
toml = "0.9.5"
clap = { version = "4.5.6", features = ["derive"] }

[patch.crates-io]
iced = { git = "https://github.com/iced-rs/iced", rev = "49a300ab38a86d548b5a607113827ac9efdcf2f9" }
iced_core = { git = "https://github.com/iced-rs/iced", rev = "49a300ab38a86d548b5a607113827ac9efdcf2f9" }
