[general]
background = "#282828"
background_success = "#98971a"
background_failure = "#cc241d"
border = "#504945"
scrollbar = "#1d2021"
horizontal_rule = "#3c3836"

[buffer]
background = "#3c3836"
background_title_bar = "#458588"
border = "#1d2021"
border_focus = "#458588"

[text]
primary = "#ebdbb2"
secondary = "#a89984"
tertiary = "#504945"
success = "#b8bb26"
error = "#fb4934"
warning = "#fabd2f"
info = "#83a598"
debug = "#fe8019"
trace = "#fbf1c7"


[button.primary]
background = "#282828"
background_hover = "#252525"
background_selected = "#202020"
background_selected_hover = "#151515"

[button.secondary]
background = "#323034"
background_hover = "#3e3c41"
background_selected = "#606155"
background_selected_hover = "#6f7160"

[button.dangerous]
background = "#9d0006"
background_hover = "#cc241d"
background_selected = "#cc241d"
background_selected_hover = "#fb4934"
