[general]
background = "#282828"
border = "#504945"

[buffer]
background = "#3c3836"
background_title_bar = "#83a589"
border = "#1d2021"
border_focus = "#83a589"

[text]
primary = "#fbf1c7"
secondary = "#ebdbb2"
tertiary = "#d5c4a1"

[button.primary]
background = "#282828"
background_hover = "#252525"
background_selected = "#202020"
background_selected_hover = "#151515"

[button.secondary]
background = "#323034"
background_hover = "#3e3c41"
background_selected = "#606155"
background_selected_hover = "#6f7160"
